name: Bump Files Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      # Checkout action is required
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './bump/options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
